### ISSUE TITLE
ModuleNotFoundError: No module named 'rvc_infer'

### ISSUE THREAD

**Issue by deeplearner5** [JarodMica/audiobook_maker#8]
I haven't seen any other reference to this, so its likely an issue at my end, but inside the venv, when I call audio_book_app_2_0.py, I get a ModuleNotFoundError for rvc_infer

rvc_infer seems to have installed correctly as part of rvc-tts-pipeline, i.e.:
pip install -e git+https://github.com/JarodMica/rvc-tts-pipeline.git#egg=rvc_tts_pipe
...
Successfully installed rvc_tts_pipe-0.1

Any ideas on what may be happening here? I see no errors in any of the installations, other than a deprecation warning.
Thanks
DL5

**Comment by JarodMica** [comment]
If you are in vscode, make sure that the venv is also selected as the active interpreter which can be changed at the bottom right corner of the screen.

If not, could you try uninstalling both the rvc-tts-pipe and then rvc?

You can do this by:

```pip uninstall rvc-tts-pipe```

```pip uninstall rvc```

Then try reinstalling them.  If that doesn't work, delete the venv, and then start installation from scratch to see if that works.

**Comment by deeplearner5** [comment]
Hmm - am definitely in the venv, and reinstalling, both packages and full venv, still gives the same issue.

It seems to be something to do with the install of rvc-tts-pipe - I see lib/site-packages/rvc-tts-pipe-0.1.dist-info, but there's no matching lib/site-packages/rvc-tts-pipe , ditto for rvc. I can see both source packages in venv/src/ just fine though.

It may just be something borked in my setup (python 3.9.10, CUDA 11.7, Windows 10 - outside the venv I have RVC and Tortoise all working fine), so don't worry, unless someone else gets the same issue. It's just a bit weird that I don't see any issues in the installation, it claims to install normally.
Thanks
DL5

**Comment by Romanio1997** [comment]
(venv) c:\AI\audiobook_maker>audio_book_app_2_0.py
Traceback (most recent call last):
  File "C:\AI\audiobook_maker\audio_book_app_2_0.py", line 15, in <module>
    from rvc_infer import rvc_convert
ModuleNotFoundError: No module named 'rvc_infer' same error.

**Comment by sunbart** [comment]
Ok, so I got the same error and resolved it by not updating my pip before running the installation steps.

Just to be explicit:

- I created my venv using `py.exe -3.10 -m venv venv` (because I also have python 3.11, so I used py.exe to force 3.10 to be safe)
- Installed the `requirements.txt` file and got this notice 
![image](https://github.com/JarodMica/audiobook_maker/assets/9112056/ba7e4d4e-e012-479c-8ced-92399d062c28)
- Ran the command recommended by that notice
- Continued on with the other installation steps in readme

Then, executing `audio_book_app_2_0.py` both from CLI or via VSCode's run menu (both with and without debug), the rvc_infer module was missing. (Yes, I did have the venv active)

When I skip the step where I update pip, the script works, the GUI opens and everything seems good. (I get an error a little later on, but I'll make a new issue for that)

**Comment by deeplearner5** [comment]
@sunbart - can confirm that works for me too, great spot.  There must be some subtlety in pip=23.2.1 that borks the install.

@JarodMica - I'd suggest this resolves the issue, if you're also happy?
Thanks
DL5

**Comment by sunbart** [comment]
I suspect paying attention to "future deprecation" warnings that are emitted by pip 23.0 that are absent when using pip 23.2 should help in figuring out what the actual cause is. 

My assumption is that there is some deprecation between the two versions is what causes it. 

Just from a cursory look, pip 23.0 does indeed emit significantly more warning messages than 23.2

**Comment by JarodMica** [comment]
@sunbart @deeplearner5 Thanks for the updates guys, I totally forgot about incompatibilities with building if pip isn't updated, though, I wonder what package is causing the issue.  I leave it at that for now for having solved this issue.

**Comment by jigsaw490216** [comment]
@sunbart Thanks for the help am no code person and i have no clue about codes and other things but with your explanation i managed to fix the error
