### ISSUE TITLE
Error loading fbgemm.dll or one of its dependencies

### ISSUE THREAD

**Issue by theaiguy3007** [JarodMica/audiobook_maker#96]
I did all like the instructions. but when I start I get the following error

![image](https://github.com/user-attachments/assets/f92b18fd-546d-4a6f-bbb3-23b836fe1d8e)

**Comment by theaiguy3007** [comment]
btw, same with my package I bought. After all installation this is the error. I thought maybe Im too stupid fpr manual installation and bought the package

![image](https://github.com/user-attachments/assets/b4115d68-8a3b-4605-96ab-26f3f150ccd1)

**Comment by JarodMica** [comment]
> btw, same with my package I bought. After all installation this is the error. I thought maybe Im too stupid fpr manual installation and bought the package
> 
> ![image](https://private-user-images.githubusercontent.com/189520123/389269519-b4115d68-8a3b-4605-96ab-26f3f150ccd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0ODM5NzMsIm5iZiI6MTczMjQ4MzY3MywicGF0aCI6Ii8xODk1MjAxMjMvMzg5MjY5NTE5LWI0MTE1ZDY4LThhM2ItNDYwNS05NmFiLTI2ZjNmMTUwY2NkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQyMTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTA5MzkwZTEzMzMwYmUwYTIxYzUyZTcwMjNkNmNmMWI3Y2QzNmY0NzBmZTY2MmU3YTA5NWZjM2JhYzA2OTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I32oz6GQuooVYEuAY4DZsFHGmFt05Jra65N0s7UiXsY)

So it seems to be due to a library missing on your windows install - I went through this post here and there are a few things you can try: https://github.com/pytorch/pytorch/issues/131662

1. The easiest would be to try torch with a newer version, if this works, I'll have to update the version of torch being used. To test this, download the follow script and place it into the audiobook maker package.  Due to github restrictions, change the name and remove the .txt from the end to turn it back into a batch script. [update_torch.bat.txt](https://github.com/user-attachments/files/17895096/update_torch.bat.txt) then run the script.

Afterwards, test to see if start.bat will work and launche without issue. If not, try the next step

2. Download and install Visual Studio 2022 with Desktop development with C++ to get the .dll file.  Follow the post here: https://github.com/pytorch/pytorch/issues/131662#issuecomment-2253733324

After that, try the same, launch start.bat.

Let me know how that goes.  If neither of these works, I can search around and find the .dll files on my PC to share

**Comment by theaiguy3007** [comment]
Perfect. I will check this evening and let you know.Thank you for the quick responseAm 24.11.2024 um 23:02 schrieb Jarod Mica ***@***.***>:﻿

btw, same with my package I bought. After all installation this is the error. I thought maybe Im too stupid fpr manual installation and bought the package


So it seems to be due to a library missing on your windows install - I went through this post here and there are a few things you can try: pytorch/pytorch#131662

The easiest would be to try torch with a newer version, if this works, I'll have to update the version of torch being used. To test this, download the follow script and place it into the audiobook maker package.  Due to github restrictions, change the name and remove the .txt from the end to turn it back into a batch script. update_torch.bat.txt then run the script.

Afterwards, test to see if start.bat will work and launche without issue. If not, try the next step

Download and install Visual Studio 2022 with Desktop development with C++ to get the .dll file.  Follow the post here: pytorch/pytorch#131662 (comment)

After that, try the same, launch start.bat.
Let me know how that goes.  If neither of these works, I can search around and find the .dll files on my PC to share

**Comment by theaiguy3007** [comment]
Okay, so pyttsx3 seems to bee working. If I follow the instructions from your video, and for example use "DeepSpeed" I get the following error:

![image](https://github.com/user-attachments/assets/19e9e4f2-4a57-4676-a889-009479531686)

**Comment by JarodMica** [comment]
> Okay, so pyttsx3 seems to bee working. If I follow the instructions from your video, and for example use "DeepSpeed" I get the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/189520123/389682795-19e9e4f2-4a57-4676-a889-009479531686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Mjc1MjYsIm5iZiI6MTczMjgyNzIyNiwicGF0aCI6Ii8xODk1MjAxMjMvMzg5NjgyNzk1LTE5ZTllNGYyLTRhNTctNDY3Ni1hODg5LTAwOTQ3OTUzMTY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMDUzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDc1NzcyNWY4NjUzMTcwZGI3NmRhZTgyNTc0ZmVlZjg0ZThhZTlmMzFjZDE0OTE0NGJmMTU5OTdkNjQ2YThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZXrbgRQ7sx-KeRCq2kjJB_A9BO_FLlbRCS6TuVYmgGQ)
> 
> and also this one now when starting
> 
> ![image](https://private-user-images.githubusercontent.com/189520123/389684321-ac8637d3-fa80-4aa4-9ea7-8e8a10622ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Mjc1MjYsIm5iZiI6MTczMjgyNzIyNiwicGF0aCI6Ii8xODk1MjAxMjMvMzg5Njg0MzIxLWFjODYzN2QzLWZhODAtNGFhNC05ZWE3LThlOGExMDYyMmViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMDUzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDUxNTk3NDMwNGY0YmZiNjcyYWQwZDcwYTg0ZmY3ZmJhYTZhMjQwOGIzNjEzZjkxN2Q0ZTA1ODJjMjI1ZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ncewFqd1wywdKcYx1ksoeydU8gE9muFiMtEoQ9a6lJ0)

Awesome! I'm glad to hear it's working after that update. 

Unfortunately, I broke deepspeed updating torch versions, so I'll need to change a few things and it isn't useable ATM due to: https://github.com/JarodMica/audiobook_maker/issues/100

As for the latest error, can you download the cuda toolkit here: https://github.com/JarodMica/audiobook_maker?tab=readme-ov-file#pre-requisites

It's required even for the package build right now

**Comment by theaiguy3007** [comment]
Works for me atm. Looking forward on further updates thank you so far :)
